Fix 415 error
tsibelman/aws-signer-v4-dot-net pull request #19
Opened 2019-09-17 14:14 UTC by ronenfe

2019-09-17 14:16 UTC, tsibelman requested changes

2019-09-17 14:16 UTC, tsibelman commented on Aws4Signer/AWS4RequestSigner.cs
> +namespace AWS4RequestSigner
Please preserve name space it would be a breaking change.

2019-09-17 14:16 UTC, tsibelman commented on Aws4Signer/Aws4RequestSigner.csproj
> +    <SignAssembly>false</SignAssembly>
Revert to true

2019-09-17 14:17 UTC, tsibelman commented
Increase assembly version

2019-09-18 09:40 UTC, ronenfe commented
done

2019-09-18 09:49 UTC, tsibelman approved these changes

2019-09-18 15:16 UTC, tsibelman approved these changes

2019-09-18 15:16 UTC, merged